name: Build htdocs

on:
  push:
    branches:
      - master
    paths:
      - 'web-src/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Build for production with minification (will update web interface
      # in "../htdocs")
      - name: Build htdocs
        working-directory: web-src
        run: |
          npm install
          npm run build

      - name: Show staged changes
        run: |
          git add --force htdocs/
          git status

      - name: Commit and push updated repo
        run: |
          git config --global user.name 'Espen Jürgensen'
          git config --global user.email 'espenjurgensen@gmail.com'
          git commit -am "Automatic repository update"
          git push
