name: FreeBSD

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - 'htdocs/**'
      - 'web-src/**'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - 'htdocs/**'
      - 'web-src/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      uses: vmactions/freebsd-vm@v1
      with:
        prepare: |
    	    pkg install -y gmake autoconf automake libtool gettext gperf glib pkgconf wget ffmpeg libconfuse libevent libxml2 libgcrypt libunistring libiconv curl libplist libinotify avahi sqlite3 alsa-lib libsodium json-c libwebsockets protobuf-c bison flex

        configure: |
          export CFLAGS="${ARCH} -g -I/usr/local/include -I/usr/include"
          export LDFLAGS="-L/usr/local/lib -L/usr/lib"
          ./configure --disable-install-systemd

        build: |
          gmake
          gmake install
