name: m2

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install build tools
      run: |
        brew install automake autoconf libtool pkg-config gettext
        brew --prefix
        aclocal --print-ac-dir
        ls $(brew --prefix)/share/aclocal
        ls $(brew --prefix)/share/gettext/m4
